export default function Head() {
  return (
    <>
      <title>Nutryphyll</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/svg+xml" href="./app_bar_logo.png" />
    </>
  );
}
